# Generated by Django 4.2.7 on 2024-01-09 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_alter_sporttype_icon'),
        ('utils', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportdata',
            name='attr',
            field=models.CharField(max_length=255, verbose_name='Qisqa nomi [attr]'),
        ),
        migrations.AlterField(
            model_name='sportdata',
            name='attr_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Qisqa nomi [attr]'),
        ),
        migrations.AlterField(
            model_name='sportdata',
            name='attr_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Qisqa nomi [attr]'),
        ),
        migrations.AlterField(
            model_name='sportdata',
            name='attr_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Qisqa nomi [attr]'),
        ),
        migrations.AlterField(
            model_name='sportdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='sportdata',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Chop etilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='sportdata',
            name='sport_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.sporttype', verbose_name='Sport turi'),
        ),
        migrations.AlterField(
            model_name='sportdata',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.state', verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='sportdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti'),
        ),
        migrations.AlterField(
            model_name='sportdata',
            name='url',
            field=models.CharField(max_length=255, verbose_name='Youtube url'),
        ),
        migrations.AlterField(
            model_name='sportdata',
            name='views',
            field=models.IntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
        migrations.CreateModel(
            name='LegislativeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="To'liq nomi [title]")),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]")),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]")),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]")),
                ('attr', models.CharField(max_length=255, verbose_name='Qisqa nomi [attr]')),
                ('attr_uz', models.CharField(max_length=255, null=True, verbose_name='Qisqa nomi [attr]')),
                ('attr_en', models.CharField(max_length=255, null=True, verbose_name='Qisqa nomi [attr]')),
                ('attr_ru', models.CharField(max_length=255, null=True, verbose_name='Qisqa nomi [attr]')),
                ('url', models.CharField(max_length=255, verbose_name='Lex url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.state', verbose_name='Holati')),
            ],
            options={
                'verbose_name': 'Qonun hujjatlari',
                'verbose_name_plural': 'Qonun hujjatlari',
                'db_table': 'legislative_document',
            },
        ),
    ]
