# Generated by Django 4.2.7 on 2024-01-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_sportdata_attr_alter_sportdata_attr_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportdata',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Muallif'),
        ),
        migrations.AddField(
            model_name='sportdata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Rasm'),
        ),
        migrations.AddField(
            model_name='sportdata',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nashriyot'),
        ),
        migrations.AlterField(
            model_name='sportdata',
            name='published_at',
            field=models.DateField(blank=True, null=True, verbose_name='Chop etilgan vaqti'),
        ),
    ]
