# Generated by Django 4.2.7 on 2024-01-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sportdata_author_sportdata_image_sportdata_publisher_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sportdata',
            index=models.Index(fields=['sport_type', 'state', 'created_at'], name='sport_data_sport_t_4f1421_idx'),
        ),
    ]
