# Generated by Django 4.2.7 on 2024-01-11 06:10

from django.db import migrations, models
import django.utils.translation


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sportdata_sport_data_sport_t_4f1421_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportdata',
            name='language',
            field=models.CharField(blank=True, choices=[('uz', "O'zbek tili"), ('en', 'English'), ('ru', 'Russian')], default=django.utils.translation.get_language, max_length=2, null=True, verbose_name='Til'),
        ),
    ]
