# Generated by Django 4.2.7 on 2024-01-11 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Tizim haqimizda', 'verbose_name_plural': 'Tizim haqimizda'},
        ),
        migrations.AlterModelTable(
            name='about',
            table='about',
        ),
    ]
