# Generated by Django 4.2.7 on 2024-01-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_about_options_alter_about_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='content_en',
            field=models.TextField(null=True, verbose_name="Ma'lumot"),
        ),
        migrations.AddField(
            model_name='about',
            name='content_ru',
            field=models.TextField(null=True, verbose_name="Ma'lumot"),
        ),
        migrations.AddField(
            model_name='about',
            name='content_uz',
            field=models.TextField(null=True, verbose_name="Ma'lumot"),
        ),
        migrations.AddField(
            model_name='about',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
        migrations.AddField(
            model_name='about',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]"),
        ),
    ]
