# Generated by Django 4.2.7 on 2024-01-22 05:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_footer_options_sportdata_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportdata',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True, verbose_name='UUID'),
        ),
    ]
