# Generated by Django 4.2.7 on 2024-01-23 09:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_sportdata_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportdata',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Youtube url'),
        ),
        migrations.AlterField(
            model_name='sportdata',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID'),
        ),
    ]
