version: "3"
services:
  open-data.sport.service:
    image: postgres:13.1-alpine
    restart: always
    container_name: "${PROJECT_NAME}-postgres"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - ${DB_PORT}:5432


  redis-service:
    image: redis:6.0.9-alpine
    container_name: "${PROJECT_NAME}-open-data-redis"
    expose:
      - 6379


