# Generated by Django 4.2.7 on 2024-01-09 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="To'liq nomi [title]")),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]")),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]")),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name="To'liq nomi [title]")),
                ('attr', models.CharField(max_length=255, verbose_name='qisqa nomi [attr]')),
                ('attr_uz', models.CharField(max_length=255, null=True, verbose_name='qisqa nomi [attr]')),
                ('attr_en', models.CharField(max_length=255, null=True, verbose_name='qisqa nomi [attr]')),
                ('attr_ru', models.CharField(max_length=255, null=True, verbose_name='qisqa nomi [attr]')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='tahrirlangan vaqti')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.state', verbose_name='holati')),
            ],
            options={
                'verbose_name': 'Sport turi',
                'verbose_name_plural': 'Sport turlari',
                'db_table': 'sport_type',
            },
        ),
    ]
