# Generated by Django 4.2.7 on 2024-01-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporttype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='icon'),
        ),
    ]
