# Generated by Django 4.2.7 on 2024-01-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_sporttype_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporttype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='Ikonka kiriting'),
        ),
    ]
